### ISSUE TITLE
Character Generation - Character wears helmet, features hard to make out

### ISSUE THREAD

**Issue by J-Paine** [Kvitekvist/FUS#1]
When you are creating a new character, the character (tested male Nord and male Orc) wears a face covering helmet. Can't actually see what kind of face I am making.

**Comment by MariusKlug** [comment]
This was a feature of AI Overhaul but we decided to remove it and roll with the basic naked start since Real of Lorkhan provides plenty of equipment option anyways. Fixed in v1.0.1
