### ISSUE TITLE
new grass setup

### ISSUE THREAD

**Issue by MariusKlug** [Kvitekvist/FUS#14]
replace cathedral landscapes by the grass your mum warned about: https://www.nexusmods.com/skyrimspecialedition/mods/53064

also add https://www.nexusmods.com/skyrimspecialedition/mods/9005 and the patch from tgymwa

also add fallen leaves in the Rift: green (summer) -> download, unzip, remove the other option, rezip, add to mo2

still let 3d pine grass overwrite this mod as it is better in vr (https://www.nexusmods.com/skyrimspecialedition/mods/42032?tab=files). also add "Cathedral - 3D Pine Grass - Full 3D Coverage" and "High Poly Green Grass Update" as an optional file (disabled by default).

make sure the imingrasssize in the two mods is set to 80!

this will require a rerun of xlodgen landscape lods. in my tests I needed a brightness of +8 to have it blend nicely, but this may be because of some oddity in my setup. try it out :)

**Comment by MariusKlug** [comment]
add waterplants lily only from here, too: https://www.nexusmods.com/skyrimspecialedition/mods/6092?tab=files (this isn't technically grass but still)

**Comment by Kvitekvist** [comment]
added with patches.
