### ISSUE TITLE
Water is much too blue to be realistic

### ISSUE THREAD

**Issue by J-Paine** [Kvitekvist/FUS#2]
Tested with VrVision, then with Sensorium ENB. Both have water that is much too blue.
![OculusScreenshot1628195582](https://user-images.githubusercontent.com/87666294/128438052-4ec6b91f-9c96-4238-9074-bd719bf16eff.jpeg)

**Comment by J-Paine** [comment]
![OculusScreenshot1628225272](https://user-images.githubusercontent.com/87666294/128460929-6455c297-36ba-478a-af5c-901f9e75be5b.jpeg)

**Comment by J-Paine** [comment]
After entering Whiterun, then fast traveling back.... Perfect water. I could literally gush about how good the water/sensorium combo is. Fantastic. But I changed _nothing_ to go from the cartoon blue to realistic.

**Comment by J-Paine** [comment]
Moved Synthesis after dynDOLOD in the priority order and have had no super blue water issues since.
![OculusScreenshot1628373687](https://user-images.githubusercontent.com/87666294/128615272-df79e7dd-e99a-4a9d-b886-995e57501b57.jpeg)

**Comment by J-Paine** [comment]
W Northern Shores/Hyperborean Snow/Septentrional and the experimental extra foggy sensorium ENB. I love how this looks on my system. This fidelity is on a 90fps 99+% of the time setup.

**Comment by MariusKlug** [comment]
Fixed in v 1.0.1
