### ISSUE TITLE
Kvite - where is the dyndolod settings? :D

### ISSUE THREAD

**Issue by J-Paine** [Kvitekvist/FUS#3]
Would like to experiment with adding terrain textures (Septentrional darn it),  and would like to maintain the awesome level of dyndolod that is currently in the modlist. Please share dyndolod settings!

**Comment by Kvitekvist** [comment]
Dyndolod settings are now added to the readme https://github.com/Kvitekvist/FUS/tree/main/images/lod%20settings

**Comment by MariusKlug** [comment]
Comment about the images added to FAQ
