### ISSUE TITLE
Can't add a second Steam library on the C:\ drive

### ISSUE THREAD

**Issue by ryankrage77** [Kvitekvist/FUS#34]
The [Install Skyrim](https://github.com/Kvitekvist/FUS/wiki/Prepare-PC-for-modlist#install-skyrim) instructions say to create a new Steam library outside of `C:\Program Files (x86)\`, for example at `C:\SteamLibrary`.

The Steam client only allows one library per drive.
![Screenshot 2021-12-26 073113](https://user-images.githubusercontent.com/25205800/147401826-17665924-c138-4a3d-8788-21d16d3b9dd5.png)

Methods to circumvent this such as [editing the libraryfolders.vdf](https://www.reddit.com/r/Steam/comments/pr7tuf/create_second_steam_library_on_same_drive_2021/hf9yvgu/) file no longer work, as Steam reverts any changes made once the client is re-launched.

Can I install Skyrim to `D:\SteamLibrary` if my FUS and Wabbajack folders are on the `C:\` drive?
Will I need to download all the mods again if I change the location of the FUS/Wabbajack folders?

**Comment by Kvitekvist** [comment]
Yes you can install it on D drive m, no problem

**Comment by MariusKlug** [comment]
Also: Small tool to add additional library folders to Steam - Usage Guide · LostDragonist/steam-library-setup-tool Wiki

https://github.com/LostDragonist/steam-library-setup-tool/wiki/Usage-Guide
