### ISSUE TITLE
Character texture mods don't seem to work

### ISSUE THREAD

**Issue by marcinkeviciusp** [Kvitekvist/FUS#37]
I've been adding additional mods and I think this based on the following:

-> I've successfully installed CBBE 3BA and the model aspect of it works fine, but the textures don't seem to match the body anymore
-> Installing another character texture mod on top does nothing (tried 3 different ones)
-> All other texture mods seem to be working (weapons, animals)

It might be my inexperience causing this, tho it's kinda sus everything else works...

**Comment by MariusKlug** [comment]
we do not provide support for adding mods. the list is curated as-is, if you add stuff, you are on your own.
