### ISSUE TITLE
Unable to download Skyrim.ini

### ISSUE THREAD

**Issue by nikita-korovin** [Kvitekvist/FUS#42]
Hey!
Having this problem (log file)
FATAL ] (Wabbajack.Installer.StandardInstaller) Unable to download Skyrim.ini (GameFileSourceDownloader+State|SkyrimVR|1.4.15.0|skyrim.ini)

**Comment by MariusKlug** [comment]
Try closing and restarting Wabbajack a few times. For more support on this please visit the discord! https://discord.gg/Kv6MdXY3fB
