### ISSUE TITLE
Where to place LOTD and how to install patch from Lanterns of Skyrim II for LOTD

### ISSUE THREAD

**Issue by Calendrigame** [Kvitekvist/FUS#45]
Hello, 
I wanted to install LotD mod but normally i put quest mods very high in the load order. Only i asked for help elswere first and they told me to run the LotD and its patchers after all FUS mods. Is that correct? Because I don't know and I don't want to mess things up.

My second question was about Lanterns of Skyrim II. It uses a patch for LotD. I can find it in the FOMOD of LoSII when i try to download it from the site. But how do I implement this in FUS? Should i just reinstall the whole mod with the patch? So, remove reinstall? Of is there another way? I hope you can help me with his. 

I came to ask here since I couln't get an reliable and understandable sollution elswere. 

Kind regards and Ty for all the work making this mod pack. 

Inka

**Comment by Kvitekvist** [comment]
Hello!

Unfortunatly, we dont offer offical support for "how to add mods" to the modlist.
BUT there is a section in our FUS discord for unsupported questions like this that u can ask in or browse through. LOTD has been mentioned there before.

Enjoy the list :D
