### ISSUE TITLE
Reinstalling ENBs

### ISSUE THREAD

**Issue by f-lng** [Kvitekvist/FUS#46]
Hello guys,

I understand your reasoning behind removing ENBs from the modlist, but as a first-time SkyrimVR player I would like to at least give it a try :) 

Would you be so kind to at least point me into the right direction on how to install it into the current version of the modlist without breaking everything? 

Would be much appreciated. Thank you in advance for any help you can provide.

**Comment by Kvitekvist** [comment]
We have stopped the offical support of ENBs, so we wont be providing step by step guides for adding ENB (or any other mod not already in FUS).

What you can do is either download a previous version of FUS with ENB and copy the setup from that, or check google for "how to install ENB" as there are several guides on this topic. 

We use rootbuilder to inject mods like ReShade, and thats how we dealt with ENB as well. So look into ENB + Rootbuilder. Good luck! :D
