### ISSUE TITLE
Copying mods between different versions of FUS without breaking the whole thing

### ISSUE THREAD

**Issue by f-lng** [Kvitekvist/FUS#47]
Hello guys,

I understand your different reasons for removing some mods from one version to the other.

What would be the process of (re)adding a discontinued mod of any kind back to the current FUS release, by copying it over from an older release? 

Given that the whole modlist is build on top of a variety of tools (wabbajack, modorganizer, root builder etc.) at once this process is unfortunately not easily understood, especially by someone new to Skyrim modding.

Any pointers and help would be much appreciated. Thanks!

P.S: Kvitekvist, excuse the audacity of the question, but I have to try, right? :)

**Comment by Kvitekvist** [comment]
In the intro of the readme we state "NOTE: We only provide support on unmodified versions of FUS."
Adding, removing, changing or updating mod falls into this. So Cangar and I will not advice on it.

In the discord there are 2 suitable channels where you can ask these questions and hope that the community will advice :)

that is the "unsupported-mod-discussion-fus" or the "community-guides", the latter is intended as a place where the community post guides on adding stuff to FUS, but totally has nothing to do with Cangar and I. Try there :)

**Comment by f-lng** [comment]
Ok, thank you :) And btw, great work with the list!
