### ISSUE TITLE
Doesn't launch anymore

### ISSUE THREAD

**Issue by Thryphore** [Kvitekvist/FUS#49]
Tried using this mod today but it doesn't launch. It just pulls up an empty command prompt and then doesn't launch
![image](https://github.com/Kvitekvist/FUS/assets/54916525/51e9900e-bb70-45d6-a100-d3acede9c946)
The mods aren't in the folder things like they should be. Maybe this has something to do with it?

**Comment by Kvitekvist** [comment]
Your mods are no longer sorted by the field named "Priority". If you click on the header "Priority" it will sort them correctly.
If it still does not work, then rerun wabbajack to restor the list factory default.

**Comment by Thryphore** [comment]
I had 2 reshade options clicked for whatever reason which I couldn't see because they were out of order. Thanks for your help
