### ISSUE TITLE
Wabbajack did not find the skyrimvr steam game before a pc restart

### ISSUE THREAD

**Issue by Xostan** [Kvitekvist/FUS#51]
Wabbajack did not find the skyrimvr steam game. a pc restart fixed it for me. This should be mentioned in the readme.
May only occur if skyrimvr is installed while wabbajack is already running.

**Comment by MariusKlug** [comment]
Updated https://github.com/Kvitekvist/FUS/wiki/Wabbajack-Troubleshooting at the section where WJ did not find the game folder.
