### ISSUE TITLE
Skyrim ini trouble

### ISSUE THREAD

**Issue by Levris** [Kvitekvist/FUS#52]
After installing all the files I received the following error in the log - "Unable to download Skyrim.ini (GameFileSourceDownloader+State|SkyrimVR|1.4.15.0|skyrim.ini)"

**Comment by 8Nuppu8** [comment]
Changing the language on Steam to English helped me

**Comment by jhb96** [comment]
Same, the problem was the language in Steam game!

**Comment by MariusKlug** [comment]
Yes only English is supported I am afraid. If your language is EN and you still get these errors, verify your game files in Steam.
