### ISSUE TITLE
Add information regarding "root builder" to README.md

### ISSUE THREAD

**Issue by JHawkley** [Kvitekvist/FUS#56]
In the `README.md` file, under the section "First Boot", it is stated:

> Any time you make a change to mods in mod category 1.1 and 1.2 you need to clean up the root builder. Check the !root command in our discord for more information on this.

You should put this important information about the root builder here, in the readme.  There's no reason I can see to force a user to join a Discord server to run a command in order to receive a blurb of text from a bot that could ...just be in the readme.

**Comment by MariusKlug** [comment]
added
